"""Generate frontend/lib/types.ts from Pydantic schemas.

Usage: ``python scripts/generate_ts_types.py``

Walks ``app.schemas``, emits a TypeScript file that mirrors the Pydantic
models 1:1 and overwrites ``../frontend/lib/types.ts``. The generator is
intentionally small (~120 lines, stdlib + pydantic) so it has no build-time
Node dependency.
"""

from __future__ import annotations

import sys
import types
from pathlib import Path
from typing import Annotated, Any, Literal, Union, get_args, get_origin

_UNION_TYPES: tuple[type, ...]
_pep604_union = getattr(types, "UnionType", None)
_UNION_TYPES = (Union, _pep604_union) if _pep604_union is not None else (Union,)

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from pydantic import BaseModel  # noqa: E402
from pydantic.fields import FieldInfo  # noqa: E402

from app import schemas  # noqa: E402

OUT_PATH = ROOT.parent / "frontend" / "lib" / "types.ts"

HEADER = (
    "// AUTO-GENERATED by backend/scripts/generate_ts_types.py — DO NOT EDIT\n"
    "// Re-run the generator any time backend/app/schemas/ changes.\n\n"
)


def _py_to_ts(tp: Any) -> str:  # noqa: PLR0911, C901
    if tp is type(None):
        return "null"
    if tp is str:
        return "string"
    if tp is bool:
        return "boolean"
    if tp is int or tp is float:
        return "number"
    if tp is Any:
        return "unknown"

    origin = get_origin(tp)
    args = get_args(tp)

    if origin is Literal:
        return " | ".join(
            f"'{a}'" if isinstance(a, str) else str(a).lower() if isinstance(a, bool) else str(a)
            for a in args
        )
    if origin is list or tp is list:
        inner = _py_to_ts(args[0]) if args else "unknown"
        return f"{inner}[]"
    if origin is dict or tp is dict:
        k = _py_to_ts(args[0]) if args else "string"
        v = _py_to_ts(args[1]) if len(args) > 1 else "unknown"
        return f"Record<{k}, {v}>"
    if origin is Annotated:
        return _py_to_ts(args[0])
    if origin in _UNION_TYPES:
        parts = [_py_to_ts(a) for a in args]
        return " | ".join(parts)

    if isinstance(tp, type) and issubclass(tp, BaseModel):
        return tp.__name__

    return "unknown"


def _render_model(model: type[BaseModel]) -> str:
    lines = [f"export interface {model.__name__} {{"]
    for field_name, field in model.model_fields.items():
        key = field.alias or field_name
        ts_type, optional = _render_field(field)
        lines.append(f"  {key}{'?' if optional else ''}: {ts_type};")
    lines.append("}")
    return "\n".join(lines)


def _render_field(field: FieldInfo) -> tuple[str, bool]:
    tp = field.annotation
    origin = get_origin(tp)
    args = get_args(tp)
    if origin in _UNION_TYPES and type(None) in args:
        non_none = [a for a in args if a is not type(None)]
        inner = _py_to_ts(non_none[0]) if len(non_none) == 1 else " | ".join(_py_to_ts(a) for a in non_none)
        return f"{inner} | null", True
    return _py_to_ts(tp), False


def _render_literal_alias(name: str, tp: Any) -> str:
    values = " | ".join(f"'{a}'" for a in get_args(tp))
    return f"export type {name} = {values};"


CHAT_EVENTS_BLOCK = """\
export interface TextEvent       { type: 'text';        content: string; }
export interface ToolCallEvent   { type: 'tool_call';   name: string; args: unknown; }
export interface ToolResultEvent { type: 'tool_result'; name: string; result: unknown; }
export interface EvidenceEvent   { type: 'evidence';    items: EvidenceItem[]; }
export interface TraceEvent      { type: 'trace';       agent?: string | null; step: string; }
export interface DoneEvent       { type: 'done'; }

export type ChatEvent =
  | TextEvent
  | ToolCallEvent
  | ToolResultEvent
  | EvidenceEvent
  | TraceEvent
  | DoneEvent;"""


def main() -> None:
    blocks: list[str] = []

    blocks.append(_render_literal_alias("SourceType", schemas.SourceType))
    blocks.append(_render_literal_alias("MessageRole", schemas.MessageRole))

    model_order = [
        schemas.Ingredient,
        schemas.Supplier,
        schemas.ConsolidationGroup,
        schemas.EvidenceItem,
        schemas.EvidenceBundle,
        schemas.Message,
        schemas.ComplianceInput,
        schemas.ComplianceResult,
        schemas.ChatRequest,
    ]
    for model in model_order:
        blocks.append(_render_model(model))

    blocks.append(CHAT_EVENTS_BLOCK)

    output = HEADER + "\n\n".join(blocks) + "\n"

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(output, encoding="utf-8")
    print(f"Wrote {OUT_PATH} ({len(output)} bytes)")


if __name__ == "__main__":
    main()
